services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    networks:
      - mynetworkdev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  blockchain-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain-scraper
    depends_on:
      - mongodb

    networks:
      - mynetworkdev
    command: ["node", "blockchain-scraper.js"]
    environment:
      MONGO_CONTAINER: mongodb-dev
      USE_TEST_SEASON: true # set to true to use the test season

  rest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-server
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
      - blockchain-scraper

    networks:
      - mynetworkdev

    # move into the rest-server folder, and run the
    # rest-server in development mode
    command: sh -c "cd ../rest-server && npm run dev"

    environment:
      MONGO_CONTAINER: mongodb-dev

    # mount the current directory into the container
    # to allow for hot-reloading
    volumes:
      - .:/app

networks:
  mynetworkdev:
    driver: bridge
