services:
  mongodb-prod:
    image: mongo:latest
    container_name: mongodb-prod
    ports:
      - "27017:27017"
    networks:
      - mynetworkprod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    # This is the volume that will be used to persist
    # the data while running in prod
    volumes:
      - ./db/data:/data/db

  blockchain-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain-scraper
    depends_on:
      - mongodb-prod

    networks:
      - mynetworkprod
    command: ["node", "blockchain-scraper.js"]
    environment:
      MONGO_CONTAINER: mongodb-prod

  rest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-server
    ports:
      - "3500:3500"
    depends_on:
      - mongodb-prod
      - blockchain-scraper

    networks:
      - mynetworkprod
    command: ["node", "../rest-server/server.js"]
    environment:
      MONGO_CONTAINER: mongodb-prod

networks:
  mynetworkprod:
    driver: bridge
