version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  # test-python:
  #   build:
  #     context: ./test-docker
  #     dockerfile: Dockerfile
  #   container_name: test-python
  #   networks:
  #     - mynetwork

  blockchain-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain-scraper
    depends_on:
      - mongodb

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
