x-global-env: &global-env
  MONGO_USER: ${MONGO_USER}
  MONGO_PASSWORD: ${MONGO_PASSWORD}
  MONGO_PORT: ${MONGO_PORT}
  MONGO_DB_NAME: ${MONGO_DB_NAME}
  MONGO_CONTAINER: mongodb-dev

services:
  auth-server:
    image: "iconcommunity/icon-wallet-auth-backend-app:1.0.2"
    container_name: auth-server
    restart: always
    ports:
      - "3005:3005"
    networks:
      - mynetworkdev
    environment:
      - NODE_ENV=production
      - JWT_SECRET="VERY SECRET SECRET TO BE CHANGED IN PRODUCTION 98237492"
      - JWT_EXPIRES_IN_S=604800
      - CHALLENGE_EXPIRATION_TIME_MS=180000
      - AUTH_TTL=60000
      - AUTH_LIMIT=300
      - CORS_ENABLED=true
      - PORT=3005
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mynetworkdev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./dev-db/data:/data/db

  blockchain-scraper:
    container_name: blockchain-scraper
    build:
      context: ./db-manager
    restart: always
    depends_on:
      - mongodb
      - rest-server
    networks:
      - mynetworkdev
    command: ["node", "blockchain-scraper.js"]
    environment:
      <<: *global-env
      DB_MANAGER_PORT: ${DB_MANAGER_PORT}
      USER_COLLECTION: ${USER_COLLECTION}
      TASK_COLLECTION: ${TASK_COLLECTION}
      SEASON_COLLECTION: ${SEASON_COLLECTION}
      USER_TASK_COLLECTION: ${USER_TASK_COLLECTION}
      REFERRALS_COLLECTION: ${REFERRALS_COLLECTION}
      USE_TEST_SEASON: true # set to true to use the test season

  rest-server:
    container_name: rest-server
    build:
      context: ./nestjs-rest-server
    restart: always
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
      - auth-server
    networks:
      - mynetworkdev
    environment:
      <<: *global-env
      NODE_ENV: prod
      LOG_LEVEL: debug
      PORT: 3500
      USE_TEST_SEASON: true # set to true to use the test season
      ICON_NETWORK: mainnet
      AUTH_URL: http://auth-server:3005

    # mount the current directory into the container
    # to allow for hot-reloading
    volumes:
      - .:/app

networks:
  mynetworkdev:
    driver: bridge
