services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  blockchain-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain-scraper
    depends_on:
      - mongodb

    networks:
      - mynetwork
    command: ["node", "blockchain-scraper.js"]
    environment:
      MONGO_CONTAINER: mongodb-dev

  rest-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-server
    ports:
      - "3500:3500"
    depends_on:
      - mongodb
      - blockchain-scraper

    networks:
      - mynetwork

    command: sh -c "cd ../rest-server && npm run dev"

    environment:
      MONGO_CONTAINER: mongodb-dev

    volumes:
      - .:/app

networks:
  mynetwork:
    driver: bridge
