---
version: "3.9"
services:
  backend:
    build: .
    ports:
      - 3500:3500
      # volumes:
      #   - .:/code
      # depends_on:
      #   - db
    # db:
    #   image: postgres:latest
    #   environment:
    #     POSTGRES_DB: mydb
    #     POSTGRES_USER: myuser
    #     POSTGRES_PASSWORD: mypassword
