export enum UserErrorCodes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  REGISTRATION_FAILED = "REGISTRATION_FAILED",
  ADDING_SEASON_FAILED = "ADDING_SEASON_FAILED",
  FAILED_TO_RETRIEVE_USER = "FAILED_TO_RETRIEVE_USER",
}
