server {

  root /var/www/butler.espanicon.team/html;
  index index.html index.htm index.nginx-debian.html;

  server_name butler.espanicon.team;

  location / {
   proxy_set_header Host $host;
   proxy_pass http://rest-server;
   proxy_next_upstream error timeout http_500;
  }


    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.espanicon.team/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.espanicon.team/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = butler.espanicon.team) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



  listen 80;
  listen [::]:80;

  server_name butler.espanicon.team;
    return 404; # managed by Certbot


}
