x-global-env: &global-env
  MONGO_USER: ${MONGO_USER}
  MONGO_PASSWORD: ${MONGO_PASSWORD}
  MONGO_PORT: ${MONGO_PORT}
  MONGO_DB_NAME: ${MONGO_DB_NAME}
  MONGO_CONTAINER: mongodb-dev

services:
  hana-rewards-backend-scraper:
    build: .
    container_name: hana-rewards-backend-scraper
    ports:
      - '3005:3005'
    environment:
      <<: *global-env
      DB_MANAGER_PORT: ${DB_MANAGER_PORT}
      USER_COLLECTION: ${USER_COLLECTION}
      TASK_COLLECTION: ${TASK_COLLECTION}
      SEASON_COLLECTION: ${SEASON_COLLECTION}
      USER_TASK_COLLECTION: ${USER_TASK_COLLECTION}
      REFERRALS_COLLECTION: ${REFERRALS_COLLECTION}
      DAILY_CHECK_IN_COLLECTION: ${DAILY_CHECK_IN_COLLECTION}
      NODE_ENV: 'production'
      RABBITMQ_URL: 'amqp://rabbitmq:5672'
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app-network
    volumes:
      - ./logs:/usr/src/app/logs # Persist log data

    command:
      [
        '/usr/src/app/wait-for-it.sh',
        'rabbitmq',
        '5672',
        '--',
        'npm',
        'run',
        'start',
      ]

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '15672:15672' # RabbitMQ management interface
      - '5672:5672' # RabbitMQ messaging port
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq # Persist RabbitMQ data
    networks:
      - app-network

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb-dev
    ports:
      - '27017:27017'
    volumes:
      - ./db-dev:/data/db # Persist MongoDB data
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

networks:
  app-network:
    driver: bridge
