version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-non-persistent
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
